#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -pe omp 16

source /etc/bashrc

module load star/2.6.0c

GENOMEDIR=/projectnb2/bf528/project_3/reference/rn4_STAR

STAR --genomeDir $GENOMEDIR --runThreadN 16 --readFilesCommand zcat \
--outSAMtype BAM SortedByCoordinate --readFilesIn /project/bf528/project_3/samples/SRR1178008_1.fastq.gz \
/project/bf528/project_3/samples/SRR1178008_2.fastq.gz \
--outFileNamePrefix SRR1178008_star_
